CANDIDATES = (
    ('bennet', 'nav', None, 'article', None, False,),
    ('biden', 'nav',  None, 'article', None, False,),
    ('booker', 'nav', None,  'article', None, False,),
    ('booker2', None, None,  'article', None, False,),
    ('buttigieg', 'nav', ('class', 'nav',), 'div', ('class', 'IssuesMain',), False,),
    ('castro', 'ul', ('class', 'header__nav',), None, None, False,),
    ('castro2', 'nav', None, 'section', None, True,),
    ('deblasio', 'ul', ('class', 'header__nav--list',),None, None, False,),
    ('delaney', 'ul', ('id', 'main-navigation',), 'main', ('id', 'main',), False,),
    ('delaney2', None, None, 'main', ('id', 'main',), False,),
    ('gabbard', 'div', ('class', 'main-menus',), 'article', ('class', 's-article',), False,),
    ('gillibrand', 'nav', ('id', 'nav-header',), 'article', None, False,),
    ('gillibrand2', None, None, 'article', None, False,),
    ('harris', 'nav', ('class', 'primary',), 'div', ('class', 'content',), False,),
    ('hickenlooper', 'nav', ('class', 'elementor-nav-menu__container',), 'div', ('data-id', '4ea4085',), False,),
    ('inslee', 'nav', ('class', 'primary',), 'article', None, False,),
    ('inslee2', None, None, 'div', ('class', 'main',), False,),
    ('klobuchar', 'ul', ('id', 'menu-main-menu',), 'div', ('class', 'article'), False,),
    ('orourke', 'nav', ('class', 'header__nav',), 'article', None, True,),
    ('ryan', 'nav', None, 'div', ('class', 'wpb_wrapper',), False),
    ('sanders', 'nav', ('id', 'menu-main-header',), 'article', None, False,),
    ('sanders2', None, None, 'article', None, False,),
    ('swalwell', 'div', ('class', 'site-nav',), 'div', ('class', 'content-wrap'), True),
    ('warren', 'nav', ('id', 'js-takeover-menu',), 'section', ('class', 'issues-lp__accordion'), True),
    ('williamson', 'nav', None, 'div', ('class', 'issues',), False,),
    ('williamson2', None, None, 'div', ('class', 'issues-section',), False,),
    ('yang', 'nav', ('class', 'nav-primary',), 'article', ('class', 'page',), False,),
    ('yang2', None, None, 'div', ('class', 'entry-content',), False,),
)
