#!/usr/bin/env python

import os
import sys

from parse_candidates import Candidate

CANDIDATES = (
    ('bennet', 'nav', None, 'article', None, False, ('https://michaelbennet.com/vision/',
                                                         'https://michaelbennet.com/vision/drive-economic-opportunity/',
                                                         'https://michaelbennet.com/vision/restore-american-values/',
                                                         'https://michaelbennet.com/vision/fix-our-broken-politics/',
                                                         'https://michaelbennet.com/climateplan/',
                                                         'https://michaelbennet.com/politicalreform/',),),
    ('biden', 'nav',  None, 'article', None, False, ('https://joebiden.com/joes-vision/',),),
    ('booker', 'nav', None,  'article', None, False, ('https://corybooker.com/issues',),),
    ('booker2', None, None,  'article', None, False, ('https://corybooker.com/issues/criminal-justice/',
                                                          'https://corybooker.com/issues/democracy-and-voting-rights/',
                                                          'https://corybooker.com/issues/equality-for-lgbtq-people/',
                                                          'https://corybooker.com/issues/equality-for-people-with-disabilities/',
                                                          'https://corybooker.com/issues/gun-violence/',
                                                          'https://corybooker.com/issues/immigration/',
                                                          'https://corybooker.com/issues/reproductive-rights/',
                                                          'https://corybooker.com/issues/college-and-workforce-training/',
                                                          'https://corybooker.com/issues/economic-security-and-opportunity/',
                                                          'https://corybooker.com/issues/health-care/',
                                                          'https://corybooker.com/issues/housing/',
                                                          'https://corybooker.com/issues/public-education/',
                                                          'https://corybooker.com/issues/climate-change-environmental-justice/',
                                                          'https://corybooker.com/issues/national-security/',
                                                          'https://corybooker.com/issues/veterans/',),),
    ('buttigieg', 'nav', ('class', 'nav',), 'div', ('class', 'IssuesMain',), False, ('https://peteforamerica.com/issues/',),),
    ('castro', 'ul', ('class', 'header__nav',), None, None, False, ('https://www.julianforthefuture.com/',),),
    ('castro2', 'nav', None, 'section', None, True, ('https://issues.juliancastro.com/people-first-immigration/',
                                                         'https://issues.juliancastro.com/people-first-education/',
                                                         'https://issues.juliancastro.com/people-first-policing/',
                                                         'https://issues.juliancastro.com/people-first-housing/',
                                                         'https://issues.juliancastro.com/eliminate-lead-exposure/',),),
    ('deblasio', 'ul', ('class', 'header__nav--list',),None, None, False, ('https://billdeblasio.com/',),),
    ('delaney', 'ul', ('id', 'main-navigation',), 'main', ('id', 'main',), False, ('https://www.johndelaney.com/issues/',),),
    ('delaney2', None, None, 'main', ('id', 'main',), True, ('https://www.johndelaney.com/issues/infrastructure/',
                                                                  'https://www.johndelaney.com/issues/artificial-intelligence/',
                                                                  'https://www.johndelaney.com/issues/health-care/',
                                                                  'https://www.johndelaney.com/issues/climate-change/',
                                                                  'https://www.johndelaney.com/issues/climate-corps/',
                                                                  'https://www.johndelaney.com/issues/commitment-to-black-america/',
                                                                  'https://www.johndelaney.com/issues/cybersecurity/',
                                                                  'https://www.johndelaney.com/issues/issues-economic-opportunity/',
                                                                  'https://www.johndelaney.com/issues/education/',
                                                                  'https://www.johndelaney.com/issues/entrepreneurship/',
                                                                  'https://www.johndelaney.com/issues/fix-our-broken-politics/',
                                                                  'https://www.johndelaney.com/issues/gun-safety/',
                                                                  'https://www.johndelaney.com/issues/heartland-fair-deal/',
                                                                  'https://www.johndelaney.com/issues/immigration/',
                                                                  'https://www.johndelaney.com/issues/lgbtq/',
                                                                  'https://www.johndelaney.com/issues/living-wage/',
                                                                  'https://www.johndelaney.com/issues/mental-health/',
                                                                  'https://www.johndelaney.com/issues/national-service/',
                                                                  'https://www.johndelaney.com/issues/negative-emissions-technologies/',
                                                                  'https://www.johndelaney.com/issues/prescription-drugs/',
                                                                  'https://www.johndelaney.com/issues/student-loans-college-affordability/',
                                                                  'https://www.johndelaney.com/issues/womens-rights/',),),
    ('gabbard', 'div', ('class', 'main-menus',), 'article', ('class', 's-article',), False, ('https://www.tulsi2020.com/about',),),
    ('gillibrand', 'nav', ('id', 'nav-header',), 'article', None, False, ('https://kirstengillibrand.com/issues/',),),
    ('gillibrand2', None, None, 'article', None, False, ('https://kirstengillibrand.com/issues/values/',
                                                             'https://kirstengillibrand.com/issues/women-and-families/',
                                                             'https://kirstengillibrand.com/issues/corruption-and-greed/',
                                                             'https://kirstengillibrand.com/issues/protecting-our-planet/',
                                                             'https://kirstengillibrand.com/issues/economy/',
                                                             'https://kirstengillibrand.com/issues/safe/',),),
    ('harris', 'nav', ('class', 'primary',), 'div', ('class', 'content',), False, ('https://kamalaharris.org/meet-kamala/',),),
    ('hickenlooper', 'nav', ('class', 'elementor-nav-menu__container',), 'div', ('data-id', '4ea4085',), False, ('https://www.hickenlooper.com/issues/',),),
    ('inslee', 'nav', ('class', 'primary',), 'article', None, False, ('https://jayinslee.com/issues',),),
    ('inslee2', None, None, 'div', ('class', 'main',), False, ('https://jayinslee.com/issues/100clean',
                                                                   'https://jayinslee.com/issues/evergreen-economy',
                                                                   'https://jayinslee.com/issues/climate-corp',
                                                                   'https://jayinslee.com/issues/americas-promise',
                                                                   'https://jayinslee.com/issues/global-climate',
                                                                   'https://jayinslee.com/issues/freedom-from-fossil-fuels',),),
    ('klobuchar', 'ul', ('id', 'menu-main-menu',), 'div', ('class', 'article'), False, ('https://amyklobuchar.com/issues/health-care/',
                                                                                            'https://amyklobuchar.com/issues/shared-prosperity-and-economic-justice/',
                                                                                            'https://amyklobuchar.com/issues/climate/',
                                                                                            'https://amyklobuchar.com/issues/a-safer-world/',
                                                                                            'https://amyklobuchar.com/issues/a-strong-democracy/',),),
    ('orourke', 'nav', ('class', 'header__nav',), 'article', None, True, ('https://betoorourke.com/kickoff-remarks/',
                                                                              'https://betoorourke.com/climate-change/',
                                                                              'https://betoorourke.com/immigration/',
                                                                              'https://betoorourke.com/lgbtq/',
                                                                              'https://betoorourke.com/choice/',
                                                                              'https://betoorourke.com/small-business/',
                                                                              'https://betoorourke.com/veterans/',
                                                                              'https://betoorourke.com/votingrights/',),),
    ('ryan', 'nav', None, 'div', ('class', 'wpb_wrapper',), False, ('https://timryanforamerica.com/issues/',),),
    ('sanders', 'nav', ('id', 'menu-main-header',), 'article', None, False, ('https://berniesanders.com/issues/',),),
    ('sanders2', None, None, 'article', None, True, ('https://berniesanders.com/issues/health-care-for-all/',
                                                          'https://berniesanders.com/issues/college-for-all/',
                                                          'https://berniesanders.com/issues/fight-for-working-families/',
                                                          'https://berniesanders.com/issues/jobs-for-all/',
                                                          'https://berniesanders.com/issues/expand-social-security/',
                                                          'https://berniesanders.com/issues/combat-climate-change-and-pass-a-green-new-deal/',
                                                          'https://berniesanders.com/issues/meet-our-commitment-to-our-veterans/',
                                                          'https://berniesanders.com/issues/enact-a-responsible-comprehensive-foreign-policy/',
                                                          'https://berniesanders.com/issues/fight-for-womens-rights/',
                                                          'https://berniesanders.com/issues/fight-for-disability-rights/',
                                                          'https://berniesanders.com/issues/fight-for-lgbtq-equality/',
                                                          'https://berniesanders.com/issues/empower-the-people-of-puerto-rico/',
                                                          'https://berniesanders.com/issues/demand-that-the-wealthy-large-corporations-and-wall-street-pay-their-fair-share-in-taxes/',
                                                          'https://berniesanders.com/issues/gun-safety/',
                                                          'https://berniesanders.com/issues/criminal-justice-reform/',
                                                          'https://berniesanders.com/issues/racial-justice/',
                                                          'https://berniesanders.com/issues/immigration-reform/',
                                                          'https://berniesanders.com/issues/empower-tribal-nations/',
                                                          'https://berniesanders.com/issues/real-wall-street-reform/',
                                                          'https://berniesanders.com/issues/fight-for-fair-trade-and-workers/',
                                                          'https://berniesanders.com/issues/reinvest-in-public-education-and-teachers/',
                                                          'https://berniesanders.com/issues/get-big-money-out-of-politics-and-restore-democracy/',
                                                          'https://berniesanders.com/issues/fair-banking-for-all/',
                                                          'https://berniesanders.com/issues/revitalizing-rural-america/',),),
    ('swalwell', 'div', ('class', 'site-nav',), 'div', ('class', 'content-wrap'), True, ('https://ericswalwell.com/my-plan/',),),
    ('warren', 'nav', ('id', 'js-takeover-menu',), 'section', ('class', 'issues-lp__accordion'), True, ('https://elizabethwarren.com/issues',),),
    ('williamson', 'nav', None, 'div', ('class', 'issues',), False, ('https://www.marianne2020.com/issues',),),
    ('williamson2', None, None, 'div', ('class', 'issues-section',), True, ('https://www.marianne2020.com/issues/child-advocacy',
                                                                                 'https://www.marianne2020.com/issues/climate-change',
                                                                                 'https://www.marianne2020.com/issues/crime-and-violence-prevention',
                                                                                 'https://www.marianne2020.com/issues/criminal-justice-reform',
                                                                                 'https://www.marianne2020.com/issues/democracy-at-risk',
                                                                                 'https://www.marianne2020.com/issues/education',
                                                                                 'https://www.marianne2020.com/issues/food',
                                                                                 'https://www.marianne2020.com/issues/gun-control',
                                                                                 'https://www.marianne2020.com/issues/healthcare',
                                                                                 'https://www.marianne2020.com/issues/immigration',
                                                                                 'https://www.marianne2020.com/issues/lgbtq-rights',
                                                                                 'https://www.marianne2020.com/issues/mass-incarceration',
                                                                                 'https://www.marianne2020.com/issues/national-security',
                                                                                 'https://www.marianne2020.com/issues/national-service',
                                                                                 'https://www.marianne2020.com/issues/native-american-reconciliation',
                                                                                 'https://www.marianne2020.com/issues/racial-reconciliation-and-healing',
                                                                                 'https://www.marianne2020.com/issues/abortion-reproductive-rights',
                                                                                 'https://www.marianne2020.com/issues/social-security',
                                                                                 'https://www.marianne2020.com/issues/the-economy',
                                                                                 'https://www.marianne2020.com/issues/veterans-support',
                                                                                 'https://www.marianne2020.com/issues/womens-rights',),),
    ('yang', 'nav', ('class', 'nav-primary',), 'article', ('class', 'page',), False, ('https://www.yang2020.com/policies/',),),
    ('yang2', None, None, 'div', ('class', 'entry-content',), False, ('https://www.yang2020.com/policies/the-freedom-dividend/',
                                                                          'https://www.yang2020.com/policies/medicare-for-all/',
                                                                          'https://www.yang2020.com/policies/human-capitalism/',
                                                                          'https://www.yang2020.com/policies/18-year-congressional-term-limits/',
                                                                          'https://www.yang2020.com/policies/end-relocation-bidding/',
                                                                          'https://www.yang2020.com/policies/public-land-preservation/',
                                                                          'https://www.yang2020.com/policies/payment-small-businesses/',
                                                                          'https://www.yang2020.com/policies/data-property-right/',
                                                                          'https://www.yang2020.com/policies/reduce-wildfires/',
                                                                          'https://www.yang2020.com/policies/prescription-drug-costs/',
                                                                          'https://www.yang2020.com/policies/restore-voting-rights/',
                                                                          'https://www.yang2020.com/policies/digital-asset-regulation/',
                                                                          'https://www.yang2020.com/policies/proportional-electors/',
                                                                          'https://www.yang2020.com/policies/expand-selective-schools/',
                                                                          'https://www.yang2020.com/policies/automatic-voter-registration/',
                                                                          'https://www.yang2020.com/policies/grid-modernization/',
                                                                          'https://www.yang2020.com/policies/head-of-culture-and-ceremony/',
                                                                          'https://www.yang2020.com/policies/dc-statehood/',
                                                                          'https://www.yang2020.com/policies/end-gerrymandering/',
                                                                          'https://www.yang2020.com/policies/reduce-packaging-waste/',
                                                                          'https://www.yang2020.com/policies/public-advisors/',
                                                                          'https://www.yang2020.com/policies/quantum-computing/',
                                                                          'https://www.yang2020.com/policies/no-pennies/',
                                                                          'https://www.yang2020.com/policies/election-day-holiday/',
                                                                          'https://www.yang2020.com/policies/empowering-mma-fighters/',
                                                                          'https://www.yang2020.com/policies/scotustermlimits/',
                                                                          'https://www.yang2020.com/policies/reviveota/',
                                                                          'https://www.yang2020.com/policies/votingage/',
                                                                          'https://www.yang2020.com/policies/cashbail/',
                                                                          'https://www.yang2020.com/policies/extend-daylight-savings-time-all-year/',
                                                                          'https://www.yang2020.com/policies/relocatefederalagencies/',
                                                                          'https://www.yang2020.com/policies/democracydollars/',
                                                                          'https://www.yang2020.com/policies/rankedchoice/',
                                                                          'https://www.yang2020.com/policies/decriminalizeopioids/',
                                                                          'https://www.yang2020.com/policies/the-freedom-dividend/',
                                                                          'https://www.yang2020.com/policies/climate-change/',
                                                                          'https://www.yang2020.com/policies/reduce-mass-incarceration/',
                                                                          'https://www.yang2020.com/policies/opioid-crisis/',
                                                                          'https://www.yang2020.com/policies/lgbtq-rights/',
                                                                          'https://www.yang2020.com/policies/foreign-policy-first-principles/',
                                                                          'https://www.yang2020.com/policies/gun-safety/',
                                                                          'https://www.yang2020.com/policies/paid-family-leave/',
                                                                          'https://www.yang2020.com/policies/support-for-the-arts/',
                                                                          'https://www.yang2020.com/policies/controlling-cost-higher-education/',
                                                                          'https://www.yang2020.com/policies/pathway-to-citizenship-2/',
                                                                          'https://www.yang2020.com/policies/southern-border-security/',
                                                                          'https://www.yang2020.com/policies/support-the-dream-act/',
                                                                          'https://www.yang2020.com/policies/right-privacy-abortion-contraception/',
                                                                          'https://www.yang2020.com/policies/overturning-citizens-united/',
                                                                          'https://www.yang2020.com/policies/fight-for-equal-pay/',
                                                                          'https://www.yang2020.com/policies/promoting-vocational-education/',
                                                                          'https://www.yang2020.com/policies/carbon-fee-dividend/',
                                                                          'https://www.yang2020.com/policies/teacher-salaries/',
                                                                          'https://www.yang2020.com/policies/early-childhood-education/',
                                                                          'https://www.yang2020.com/policies/legalization-of-marijuana/',
                                                                          'https://www.yang2020.com/policies/puerto-rican-statehood/',
                                                                          'https://www.yang2020.com/policies/value-added-tax/',
                                                                          'https://www.yang2020.com/policies/holding-pharmaceutical-companies-accountable/',
                                                                          'https://www.yang2020.com/policies/human-capitalism/',
                                                                          'https://www.yang2020.com/policies/mental-health/',
                                                                          'https://www.yang2020.com/policies/american-journalism-fellows/',
                                                                          'https://www.yang2020.com/policies/effects-smartphones-human-development/',
                                                                          'https://www.yang2020.com/policies/every-cop-gets-camera/',
                                                                          'https://www.yang2020.com/policies/ncaa-pay-athletes/',
                                                                          'https://www.yang2020.com/policies/nuclear-launch/',
                                                                          'https://www.yang2020.com/policies/downsizing-federal-workforce/',
                                                                          'https://www.yang2020.com/policies/local-journalism-fund/',
                                                                          'https://www.yang2020.com/policies/post-offices-provide-basic-banking-services/',
                                                                          'https://www.yang2020.com/policies/american-exchange-program/',
                                                                          'https://www.yang2020.com/policies/pay-president-regulators/',
                                                                          'https://www.yang2020.com/policies/white-house-psychologist/',
                                                                          'https://www.yang2020.com/policies/free-marriage-counseling/',
                                                                          'https://www.yang2020.com/policies/automatically-sunsetting-old-laws/',
                                                                          'https://www.yang2020.com/policies/prosperity-grants/',
                                                                          'https://www.yang2020.com/policies/prevent-airlines-removing-customers/',
                                                                          'https://www.yang2020.com/policies/measuring-the-economy/',
                                                                          'https://www.yang2020.com/policies/single-parent-assistance/',
                                                                          'https://www.yang2020.com/policies/medical-technology-innovation/',
                                                                          'https://www.yang2020.com/policies/autism-intervention-funding/',
                                                                          'https://www.yang2020.com/policies/rebuild-america/',
                                                                          'https://www.yang2020.com/policies/student-loan-debt/',
                                                                          'https://www.yang2020.com/policies/expanding-medical-licensure/',
                                                                          'https://www.yang2020.com/policies/support-revival-earmarks/',
                                                                          'https://www.yang2020.com/policies/medicare-for-all/',
                                                                          'https://www.yang2020.com/policies/telescoping-retirement-accounts/',
                                                                          'https://www.yang2020.com/policies/financial-counseling/',
                                                                          'https://www.yang2020.com/policies/close-skills-gap-community-college/',
                                                                          'https://www.yang2020.com/policies/life-skills-education/',
                                                                          'https://www.yang2020.com/policies/rechannel-military-spending/',
                                                                          'https://www.yang2020.com/policies/get-america-moving/',
                                                                          'https://www.yang2020.com/policies/mandatory-vacation/',
                                                                          'https://www.yang2020.com/policies/trucking-czar/',
                                                                          'https://www.yang2020.com/policies/capital-gain-carried-interest-tax/',
                                                                          'https://www.yang2020.com/policies/filing-income-taxes/',
                                                                          'https://www.yang2020.com/policies/financial-transaction-tax/',
                                                                          'https://www.yang2020.com/policies/tort-reform-reasonableness-dismissals/',
                                                                          'https://www.yang2020.com/policies/american-mall-act/',
                                                                          'https://www.yang2020.com/policies/enticing-high-skill-individuals/',
                                                                          'https://www.yang2020.com/policies/zoning/',
                                                                          'https://www.yang2020.com/policies/algorithmic-trading-fraud/',
                                                                          'https://www.yang2020.com/policies/nuclear-energy/',
                                                                          'https://www.yang2020.com/policies/modernize-voting/',
                                                                          'https://www.yang2020.com/policies/modern-time-banking/',
                                                                          'https://www.yang2020.com/policies/economic-crime/',
                                                                          'https://www.yang2020.com/policies/media-fragmentation/',
                                                                          'https://www.yang2020.com/policies/making-taxes-fun/',
                                                                          'https://www.yang2020.com/policies/net-neutrality/',
                                                                          'https://www.yang2020.com/policies/regulating-ai-emerging-technologies/',
                                                                          'https://www.yang2020.com/policies/robo-calling-text-line/',),),
    )

class CandidatesManager(object):
    def __init__(self):
        candidates = {}
        self.working_dir = ''

    def write_candidate_links(self, c):
        with open('{}/links'.format(self.working_dir), 'wb') as f:
            for link in sorted(list(c.links)):
                f.write(link)
                f.write('\n')

    def write_candidate_pages(self, c):
        for page in c.pages:
            with open('{}/{}'.format(self.working_dir, page['filename']), 'wb') as f:
                for line in page['lines']:
                    f.write(line)
                    f.write('\n')

    def load_candidate(self, c):
        c.load_pages()
        self.working_dir = 'data/changes/{}'.format(c.name)
        if not os.path.exists(self.working_dir):
            os.mkdir(self.working_dir)
        self.write_candidate_links(c)
        self.write_candidate_pages(c)

    def load_candidates(self, index=-1):
        found = False
        for name, nav_tag, nav_attr, c_tag, c_attr, bad, urls in CANDIDATES:
            print name
            if len(sys.argv) > 1:
                if name == sys.argv[1]:
                    c = Candidate(name, nav_tag, nav_attr, c_tag, c_attr, bad, urls)
                    found = True
                    self.load_candidate(c)                    
            else:
                c = Candidate(name, nav_tag, nav_attr, c_tag, c_attr, bad, urls)
                self.load_candidate(c)
        if len(sys.argv) > 1 and not found:
            print 'No such candidate', sys.argv[1]
            sys.exit(1)
            

if __name__ == '__main__':
    cm = CandidatesManager()
    cm.load_candidates()
